v2 cicd testing test

diff --git a/.github/workflows/feature_07_comment.yml b/.github/workflows/feature_07_comment.yml
--- a/.github/workflows/feature_07_comment.yml
+++ b/.github/workflows/feature_07_comment.yml
@@ -32,13 +32,13 @@ jobs:
           sed -i 's#DB_PASSWORD=#DB_PASSWORD=${{ secrets.DB_PASSWORD_CICD }} #' .env.testing
           sed -i 's#<env name="DB_DATABASE" value="convert_testing"/>#<env name="DB_DATABASE" value="${{ secrets.DB_DATABASE_CICD }}"/>#' phpunit.xml
 
-      - name: Launch Linter
-        run: |
-          linter_output=$(./vendor/bin/pint)
-          if [[ $linter_output == *"FIXED"* ]]; then
-            echo "there is an error in your code format, correct it and push the code again!"
-            exit 1
-          fi
+      # - name: Launch Linter
+      #   run: |
+      #     linter_output=$(./vendor/bin/pint)
+      #     if [[ $linter_output == *"FIXED"* ]]; then
+      #       echo "there is an error in your code format, correct it and push the code again!"
+      #       exit 1
+      #     fi
 
       - name: Launch Unit Test
         run: ./vendor/bin/phpunit --testsuite Feature
