v7 continuous integration

diff --git a/.github/workflows/feature_07_comment.yml b/.github/workflows/feature_07_comment.yml
--- a/.github/workflows/feature_07_comment.yml
+++ b/.github/workflows/feature_07_comment.yml
@@ -14,8 +14,38 @@ jobs:
       - name: Get latest code
         uses: actions/checkout@v3
 
-  FTP-Deploy-Action:
-    name: FTP-Deploy-Action
+      - name: Build Apps
+        run: composer install
+
+      - name: Generate Storage
+        run: php artisan storage:link
+
+      - name: Generate Environment
+        run: cp .env.example .env.testing
+
+      - name: Generate Application Key
+        run: |
+          php artisan key:generate --env=testing
+          sed -i 's/APP_ENV=local/APP_ENV=${{ secrets.APP_ENV }}/' .env.testing
+          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=${{ secrets.DB_HOST }} /' .env.testing
+          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=${{ secrets.DB_DATABASE }} /' .env.testing
+          sed -i 's/DB_USERNAME=root/DB_USERNAME=${{ secrets.DB_USERNAME }} /' .env.testing
+          sed -i 's/DB_PASSWORD=/DB_PASSWORD=${{ secrets.DB_PASSWORD }} /' .env.testing
+          sed -i 's/<env name="DB_DATABASE" value="convert_testing"\/>/<env name="DB_DATABASE" value="${{ secrets.DB_DATABASE }}"\/>/' phpunit.xml
+
+      - name: Launch Linter
+        run: |
+          linter_output=$(./vendor/bin/pint)
+          if [[ $linter_output == *"FIXED"* ]]; then
+            echo "there is an error in your code format, correct it and push the code again!"
+            exit 1
+          fi
+
+      - name: Launch Unit Test
+        run: ./vendor/bin/phpunit --testsuite Feature
+
+  ContinuousDeployment:
+    name: FTP to server
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2.1.0
@@ -24,6 +54,6 @@ jobs:
       - name: FTP-Deploy-Action
         uses: SamKirkland/FTP-Deploy-Action@4.3.3
         with:
-          server: 142.132.150.169
-          username: user@yayasanyatimnurulanwar.biz.id
-          password: W=Ku[V;9FgSt
+          server: ${{ secrets.SERVER_FTP }}
+          username: ${{ secrets.SERVER_USERNAME }}
+          password: ${{ secrets.SERVER_PASSWORD }}
