v3 cicd fixed deleted file after 10 minutes

diff --git a/.github/workflows/feature_07_comment.yml b/.github/workflows/feature_07_comment.yml
--- a/.github/workflows/feature_07_comment.yml
+++ b/.github/workflows/feature_07_comment.yml
@@ -13,32 +13,32 @@ jobs:
       - name: Get latest code
         uses: actions/checkout@v3
 
-      - name: Build Apps
-        run: composer install
+      # - name: Build Apps
+      #   run: composer install
 
-      - name: Generate Storage Testing
-        run: php artisan storage:link
+      # - name: Generate Storage Testing
+      #   run: php artisan storage:link
 
-      - name: Generate Environment Testing
-        run: cp .env.example .env.testing
+      # - name: Generate Environment Testing
+      #   run: cp .env.example .env.testing
 
-      - name: Generate Application Key Testing
-        run: |
-          sed -i 's#APP_ENV=local#APP_ENV=testing#' .env.testing
-          sed -i "s#APP_KEY=#APP_KEY=${{ secrets.APP_KEY_CICD_CONVERT }}#" .env.testing
-          sed -i "s#DB_HOST=127.0.0.1#DB_HOST=${{ secrets.DB_HOST_CICD_CONVERT }} #" .env.testing
-          sed -i "s#DB_DATABASE=laravel#DB_DATABASE=${{ secrets.DB_DATABASE_CICD_CONVERT }} #" .env.testing
-          sed -i "s#DB_USERNAME=root#DB_USERNAME=${{ secrets.DB_USERNAME_CICD_CONVERT }} #" .env.testing
-          sed -i "s#DB_PASSWORD=#DB_PASSWORD=${{ secrets.DB_PASSWORD_CICD_CONVERT }} #" .env.testing
-          sed -i "s#<env name=\"DB_DATABASE\" value=\"convert_testing\"/>#<env name=\"DB_DATABASE\" value=\"${{ secrets.DB_DATABASE_CICD_CONVERT }}\"/>#" phpunit.xml
+      # - name: Generate Application Key Testing
+      #   run: |
+      #     sed -i 's#APP_ENV=local#APP_ENV=testing#' .env.testing
+      #     sed -i "s#APP_KEY=#APP_KEY=${{ secrets.APP_KEY_CICD_CONVERT }}#" .env.testing
+      #     sed -i "s#DB_HOST=127.0.0.1#DB_HOST=${{ secrets.DB_HOST_CICD_CONVERT }} #" .env.testing
+      #     sed -i "s#DB_DATABASE=laravel#DB_DATABASE=${{ secrets.DB_DATABASE_CICD_CONVERT }} #" .env.testing
+      #     sed -i "s#DB_USERNAME=root#DB_USERNAME=${{ secrets.DB_USERNAME_CICD_CONVERT }} #" .env.testing
+      #     sed -i "s#DB_PASSWORD=#DB_PASSWORD=${{ secrets.DB_PASSWORD_CICD_CONVERT }} #" .env.testing
+      #     sed -i "s#<env name=\"DB_DATABASE\" value=\"convert_testing\"/>#<env name=\"DB_DATABASE\" value=\"${{ secrets.DB_DATABASE_CICD_CONVERT }}\"/>#" phpunit.xml
 
-      - name: Linter
-        run: |
-          linter_output=$(./vendor/bin/pint)
-          if [[ $linter_output == *"FIXED"* ]]; then
-            echo "there is an error in your code format, correct it and push the code again!"
-            exit 1
-          fi
+      # - name: Linter
+      #   run: |
+      #     linter_output=$(./vendor/bin/pint)
+      #     if [[ $linter_output == *"FIXED"* ]]; then
+      #       echo "there is an error in your code format, correct it and push the code again!"
+      #       exit 1
+      #     fi
 
       # - name: Unit Test
       #   run: ./vendor/bin/phpunit --testsuite Feature
@@ -52,8 +52,8 @@ jobs:
       - name: Get latest code
         uses: actions/checkout@v3
 
-      - name: Build Apps
-        run: composer install
+      # - name: Build Apps
+      #   run: composer install
 
       - name: Generate Environment Production
         run: cp .env.example .env
@@ -82,17 +82,17 @@ jobs:
             .env.testing
             phpunit.xml
 
-      - name: Change App Data Location
-        run: |
-          sed -i 's|/../storage/framework/maintenance.php|/../convert_file/storage/framework/maintenance.php|g' public/index.php
-          sed -i 's|/../vendor/autoload.php|/../convert_file/vendor/autoload.php|g' public/index.php
-          sed -i 's|/../bootstrap/app.php|/../convert_file/bootstrap/app.php|g' public/index.php
-          rm -rf public/storage
+      # - name: Change App Data Location
+      #   run: |
+      #     sed -i 's|/../storage/framework/maintenance.php|/../convert_file/storage/framework/maintenance.php|g' public/index.php
+      #     sed -i 's|/../vendor/autoload.php|/../convert_file/vendor/autoload.php|g' public/index.php
+      #     sed -i 's|/../bootstrap/app.php|/../convert_file/bootstrap/app.php|g' public/index.php
+      #     rm -rf public/storage
 
-      - name: FTP-Deploy-Public
-        uses: webitsbr/github-to-ftp@1.0.1
-        with:
-          server: ${{ secrets.FTP_HOST_CONVERT }}
-          username: ${{ secrets.FTP_USERNAME_CONVERT_PUBLIC }}
-          password: ${{ secrets.FTP_PASSWORD_CONVERT_PUBLIC }}
-          local-dir: "./public/"
+      # - name: FTP-Deploy-Public
+      #   uses: webitsbr/github-to-ftp@1.0.1
+      #   with:
+      #     server: ${{ secrets.FTP_HOST_CONVERT }}
+      #     username: ${{ secrets.FTP_USERNAME_CONVERT_PUBLIC }}
+      #     password: ${{ secrets.FTP_PASSWORD_CONVERT_PUBLIC }}
+      #     local-dir: "./public/"
