v14 cicd testing test

diff --git a/.github/workflows/feature_07_comment.yml b/.github/workflows/feature_07_comment.yml
--- a/.github/workflows/feature_07_comment.yml
+++ b/.github/workflows/feature_07_comment.yml
@@ -24,14 +24,6 @@ jobs:
 
       - name: Generate Application Key Testing
         run: |
-          # sed -i 's#APP_ENV=local#APP_ENV=testing#' .env.testing
-          # sed -i "s#APP_KEY=#APP_KEY=${{ secrets.APP_KEY_CICD }}#" .env.testing
-          # sed -i "s#DB_HOST=127.0.0.1#DB_HOST=${{ secrets.DB_HOST_CICD }}#" .env.testing
-          # sed -i "s#DB_DATABASE=laravel#DB_DATABASE=${{ secrets.DB_DATABASE_CICD }}#" .env.testing
-          # sed -i "s#DB_USERNAME=root#DB_USERNAME=${{ secrets.DB_USERNAME_CICD }}#" .env.testing
-          # sed -i "s#DB_PASSWORD=#DB_PASSWORD=${{ secrets.DB_PASSWORD_CICD }}#" .env.testing
-          # sed -i "s#<env name=\"DB_DATABASE\" value=\"convert_testing\"/>#<env name=\"DB_DATABASE\" value=\"${{ secrets.DB_DATABASE_CICD }}\"/>#" phpunit.xml
-
           echo "APP_ENV=testing" >> .env.testing
           echo "APP_KEY=${{ secrets.APP_KEY_CICD }}" >> .env.testing
           echo "DB_HOST=${{ secrets.DB_HOST_CICD }}" >> .env.testing
@@ -40,16 +32,16 @@ jobs:
           echo "DB_PASSWORD=${{ secrets.DB_PASSWORD_CICD }}" >> .env.testing
           sed -i "s#<env name=\"DB_DATABASE\" value=\"convert_testing\"/>#<env name=\"DB_DATABASE\" value=\"${{ secrets.DB_DATABASE_CICD }}\"/>#" phpunit.xml
 
-      # - name: Launch Linter
-      #   run: |
-      #     linter_output=$(./vendor/bin/pint)
-      #     if [[ $linter_output == *"FIXED"* ]]; then
-      #       echo "there is an error in your code format, correct it and push the code again!"
-      #       exit 1
-      #     fi
+      - name: Launch Linter
+        run: |
+          linter_output=$(./vendor/bin/pint)
+          if [[ $linter_output == *"FIXED"* ]]; then
+            echo "there is an error in your code format, correct it and push the code again!"
+            exit 1
+          fi
 
-      # - name: Launch Unit Test
-      #   run: ./vendor/bin/phpunit --testsuite Feature
+      - name: Launch Unit Test
+        run: ./vendor/bin/phpunit --testsuite Feature
 
       # ContinuousDeployment:
       #   name: Deploy To Server
